### ISSUE TITLE
Parsing Issue in api

### ISSUE THREAD

**Issue by Archit381** [Archit381/automating-jobqueries#1]
Invalid characters/ tokens in the post method in the resume, cover letter parameter fields.

**Comment by Kshitiz-2002** [comment]
Subject: Resolution for Invalid Characters in `POST` Fields  

Dear Archit,  

To address the issue of invalid characters (e.g., quotes, commas) in the `resume` and `cover_letter` fields during `POST` requests, I developed a Streamlit-based solution. It preprocesses and sanitizes these inputs, removing problematic tokens while preserving data integrity.  

This ensures error-free submissions and improves the overall user experience. Let me know if further adjustments are needed.  

Best regards,  
Kshitiz Pandey
